package InterficiesGrafiques;

import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author agodoy.daw1r25
 */
public class ex3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ex3.class.getName());

    /**
     * Creates new form ex3
     */
    public ex3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        negreta = new javax.swing.JCheckBox();
        cursiva = new javax.swing.JCheckBox();
        vermell = new javax.swing.JRadioButton();
        blau = new javax.swing.JRadioButton();
        verd = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        camp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        negreta.setText("Negreta");
        negreta.addActionListener(this::negretaActionPerformed);

        cursiva.setText("Cursiva");
        cursiva.addActionListener(this::cursivaActionPerformed);

        buttonGroup1.add(vermell);
        vermell.setText("Vermell");
        vermell.addActionListener(this::vermellActionPerformed);

        buttonGroup1.add(blau);
        blau.setText("Blau");
        blau.addActionListener(this::blauActionPerformed);

        buttonGroup1.add(verd);
        verd.setText("Verd");
        verd.addActionListener(this::verdActionPerformed);

        camp.setColumns(20);
        camp.setRows(5);
        camp.setText("Hola mochi <3");
        jScrollPane1.setViewportView(camp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(blau)
                        .addComponent(vermell))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(verd)
                        .addGap(20, 20, 20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursiva)
                    .addComponent(negreta))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(vermell)
                        .addGap(17, 17, 17)
                        .addComponent(blau)
                        .addGap(18, 18, 18)
                        .addComponent(verd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(negreta)
                        .addGap(53, 53, 53)
                        .addComponent(cursiva))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdActionPerformed

        camp.selectAll();
        camp.setSelectionColor(Color.GREEN);
        
    }//GEN-LAST:event_verdActionPerformed

    private void cursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursivaActionPerformed
        camp.selectAll();
        
    }//GEN-LAST:event_cursivaActionPerformed

    private void negretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negretaActionPerformed

    private void blauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blauActionPerformed
        camp.selectAll();
        camp.setSelectionColor(Color.BLUE);
        
    }//GEN-LAST:event_blauActionPerformed

    private void vermellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vermellActionPerformed
        camp.selectAll();
        camp.setSelectionColor(Color.RED);
        
    }//GEN-LAST:event_vermellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ex3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea camp;
    private javax.swing.JCheckBox cursiva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox negreta;
    private javax.swing.JRadioButton verd;
    private javax.swing.JRadioButton vermell;
    // End of variables declaration//GEN-END:variables
}
