
package InterficiesGrafiques;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Ex7 extends javax.swing.JFrame {
    
    DefaultListModel<String> tasca = new DefaultListModel<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex7.class.getName());

    /**
     * Creates new form Ex7
     */
    public Ex7() {
        initComponents();
        
        jListLista.setModel(tasca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAaa = new javax.swing.JTextArea();
        jToggleButtonEliminar = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListLista = new javax.swing.JList<>();
        jComboBoxPrioritat = new javax.swing.JComboBox<>();
        jButtonAfegirTasca = new javax.swing.JButton();
        jButtonMarcarFet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTasca = new javax.swing.JTextField();
        jToggleButtonMostrarPendents = new javax.swing.JToggleButton();
        jToggleButtonMostrarFetes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaAaa.setEditable(false);
        jTextAreaAaa.setColumns(20);
        jTextAreaAaa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAaa);

        jToggleButtonEliminar.setText("Eliminar selecció");
        jToggleButtonEliminar.addActionListener(this::jToggleButtonEliminarActionPerformed);

        jScrollPane3.setViewportView(jListLista);

        jComboBoxPrioritat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Mitjana", "Baixa" }));

        jButtonAfegirTasca.setText("Afegir tasca");
        jButtonAfegirTasca.addActionListener(this::jButtonAfegirTascaActionPerformed);

        jButtonMarcarFet.setText("Marcar com a fetes");
        jButtonMarcarFet.addActionListener(this::jButtonMarcarFetActionPerformed);

        jLabel1.setText("Prioritat: ");

        jLabel2.setText("Tasca:");

        jToggleButtonMostrarPendents.setText("Mostrar pendents");
        jToggleButtonMostrarPendents.addActionListener(this::jToggleButtonMostrarPendentsActionPerformed);

        jToggleButtonMostrarFetes.setText("Mostrar fetes");
        jToggleButtonMostrarFetes.addActionListener(this::jToggleButtonMostrarFetesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonEliminar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonMostrarPendents)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonMostrarFetes)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTasca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxPrioritat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAfegirTasca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMarcarFet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPrioritat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAfegirTasca)
                    .addComponent(jButtonMarcarFet)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTasca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonEliminar)
                    .addComponent(jToggleButtonMostrarPendents)
                    .addComponent(jToggleButtonMostrarFetes))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEliminarActionPerformed
        
        int posicio = jListLista.getSelectedIndex();
        
        if (posicio != -1) {
            
            tasca.remove(posicio);
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Selecciona la tasca abans d`eliminar");
        }
    }//GEN-LAST:event_jToggleButtonEliminarActionPerformed

    private void jButtonAfegirTascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfegirTascaActionPerformed
        
        String text = jTextFieldTasca.getText();
        String tascaFinal = "✘   " + text + "      " + jComboBoxPrioritat.getSelectedItem();
        
        tasca.addElement(tascaFinal);
    }//GEN-LAST:event_jButtonAfegirTascaActionPerformed

    private void jButtonMarcarFetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarcarFetActionPerformed
        
        int posicio = jListLista.getSelectedIndex();
        
        if (posicio != -1) {
            
            String text1 = tasca.getElementAt(posicio);
            
            if (text1.startsWith("✘")) {
                
                text1 = "✔" + text1.substring(1);
                
                tasca.setElementAt(text1, posicio);
                
            } else {
                
                JOptionPane.showMessageDialog(this, "Aquesta tasca ja esta completada");
            }
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Selecciona una tasca primer", "Avís", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMarcarFetActionPerformed

    private void jToggleButtonMostrarPendentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarPendentsActionPerformed
        
        jTextAreaAaa.setText("Tasques pendents\n");
        int i = 0;
        
        while (i < tasca.getSize()){
            
            String textA = tasca.getElementAt(i);
            
            if (textA.startsWith("✘")) {
                
                jTextAreaAaa.append(textA + "\n");
            }
            
            i++;
        }
    }//GEN-LAST:event_jToggleButtonMostrarPendentsActionPerformed

    private void jToggleButtonMostrarFetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarFetesActionPerformed
        
        jTextAreaAaa.setText("Tasques fetes \n");
        int i = 0;
        
        while (i < tasca.getSize()){
            
            String textA = tasca.getElementAt(i);
            
            if (textA.startsWith("✔")) {
                
                jTextAreaAaa.append(textA + "\n");
            }
            
            i++;
        }
    }//GEN-LAST:event_jToggleButtonMostrarFetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfegirTasca;
    private javax.swing.JButton jButtonMarcarFet;
    private javax.swing.JComboBox<String> jComboBoxPrioritat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaAaa;
    private javax.swing.JTextField jTextFieldTasca;
    private javax.swing.JToggleButton jToggleButtonEliminar;
    private javax.swing.JToggleButton jToggleButtonMostrarFetes;
    private javax.swing.JToggleButton jToggleButtonMostrarPendents;
    // End of variables declaration//GEN-END:variables
}
